title: Learning React Native
description: Resources, articles, and updates for Learning React Native

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Contact
   url: /contact

social:
   github: bonniee
   twitter: brindelle
   email: contact@learningreactnative.com

google_analytics: ""
